import "./globals.css";
import type { Metadata } from "next";

import { GeistSans } from "geist/font/sans";
import { Inter, Nunito } from "next/font/google";
// import { NextUiProvider } from "./context/NextUiProvider";
// import { SuperTokensProvider } from "./context/SuperTokensProvider";
// // import { ProtectedLayer } from "./context/ProtectedLayer";
// import { TanstackProvider } from "./context/TanstackProvider";
// import { DnDProvider } from "./context/DnDProvider";
// import { ToasterContext } from "./context/ToasterContext";

import NextTopLoader from "nextjs-toploader";
import { Providers } from "./_components/Providers";

const inter = Inter({ weight: "variable", subsets: ["latin"] });

const nunito = Nunito({
  subsets: ["latin"],
  weight: "variable",
  variable: "--font-nunito",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${nunito.variable} ${GeistSans.className}`}>
      <body className="overflow-y-hidden">
        <NextTopLoader color="#000000" showSpinner={false} shadow={false} />

        {/* <SuperTokensProvider> */}
        {/* <TanstackProvider> */}
        {/* <NextUiProvider> */}
        {/* <DnDProvider> */}
        {/* <ProtectedLayer> */}
        <Providers>
          {/* <Header /> */}
          <main className="h-screen overflow-y-auto">{children}</main>
          {/* <Footer /> */}
        </Providers>
        {/* </ProtectedLayer> */}
        {/* </DnDProvider> */}
        {/* </NextUiProvider> */}
        {/* </TanstackProvider> */}
        {/* </SuperTokensProvider> */}
      </body>
    </html>
  );
}
