const baseDashboardUrl = "/dashboard/";
export const routes = {
  analytics_performance: baseDashboardUrl + "analytics_performance",
  transactionsOverview: baseDashboardUrl + "transactionsOverview",
  createFreeShipping: baseDashboardUrl + "freeShipping/create",
  accountStatements: baseDashboardUrl + "accountStatements",
  createVoucher: baseDashboardUrl + "sellerVouchers/details",
  createBundles: baseDashboardUrl + "sellerBundles/details",
  accountSettings: baseDashboardUrl + "accountSettings",
  freeShipping: baseDashboardUrl + "freeShipping/list",
  customerReturs: baseDashboardUrl + "customerReturns",
  manageProducts: baseDashboardUrl + "products/list",
  PT_performance: baseDashboardUrl + "PT_performance",
  privateTraffic: baseDashboardUrl + "privateTraffic",
  ordersOverview: baseDashboardUrl + "ordersOverview",
  displayAd: baseDashboardUrl + "marketing/displayAds",
  productAd: baseDashboardUrl + "marketing/productAds",
  adPerformance: baseDashboardUrl + "adPerformance",
  voucher: baseDashboardUrl + "sellerVouchers/list",
  bundles: baseDashboardUrl + "sellerBundles/list",
  manageQuestions: baseDashboardUrl + "questions",
  geoAnalytics: baseDashboardUrl + "geoAnalytics",
  chatSettings: baseDashboardUrl + "chatSettings",
  manageOrders: baseDashboardUrl + "orders/list",
  mediaCenter: baseDashboardUrl + "mediaCenter",
  addProduct: baseDashboardUrl + "products/add",
  helpCenter: baseDashboardUrl + "helpCenter",
  manageReviews: baseDashboardUrl + "reviews",
  contactUs: baseDashboardUrl + "contactUs",
  adGroups: baseDashboardUrl + "adGroups",
  profile: baseDashboardUrl + "profile",
  storePagesPreview: "/store/preview",
  storePagesEditor: "/store/editor",
  storeDecoration: "/store/pages",
};
