const baseDashboardUrl = "/dashboard/";
export const routes = {
  analytics_performance: baseDashboardUrl + "analytics_performance",
  bulkAddEditProducts: baseDashboardUrl + "bulkAddEditProducts",
  transactionsOverview: baseDashboardUrl + "transactionsOverview",
  accountStatements: baseDashboardUrl + "accountStatements",
  accountSettings: baseDashboardUrl + "accountSettings",
  customerReturs: baseDashboardUrl + "customerReturs",
  manageProducts: baseDashboardUrl + "manageProducts",
  PT_performance: baseDashboardUrl + "PT_performance",
  privateTraffic: baseDashboardUrl + "privateTraffic",
  ordersOverview: baseDashboardUrl + "ordersOverview",
  manageReviews: baseDashboardUrl + "manageReviews",
  adPerformance: baseDashboardUrl + "adPerformance",
  geoAnalytics: baseDashboardUrl + "geoAnalytics",
  manageOrders: baseDashboardUrl + "manageOrders",
  chatSettings: baseDashboardUrl + "chatSettings",
  mediaCenter: baseDashboardUrl + "mediaCenter",
  addProduct: baseDashboardUrl + "addProduct",
  helpCenter: baseDashboardUrl + "helpCenter",
  displayAd: baseDashboardUrl + "displayAd",
  productAd: baseDashboardUrl + "productAd",
  contactUs: baseDashboardUrl + "contactUs",
  adGroups: baseDashboardUrl + "adGroups",
  profile: baseDashboardUrl + "profile",
};
